### ISSUE TITLE
getting errors when running npm start

### ISSUE THREAD

**Issue by tempusthales** [bazomatic/windows-gsm-plugin-generator#1]
_Upon launching the npm start command the following error appears:

Z:\Github\WindowsGSM\windows-gsm-plugin-generator>npm start

```
> windows-gsm-plugin-generator@0.1.0 start Z:\Github\WindowsGSM\windows-gsm-plugin-generator
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-gsm-plugin-generator@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-gsm-plugin-generator@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TT\AppData\Roaming\npm-cache\_logs\2020-11-18T04_24_56_047Z-debug.log_
```

**Comment by bazomatic** [comment]
Not an issue per se; your dependencies are not installed, so there's no react-scripts for npm to find to run :) `npm i` in the project root resolves this, see also this [npm guide](https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/) for a more in-depth explanation of how to run npm-built apps

that said, the readme will eventually be updated with step by step execution steps, if not just outright hosting the page on heroku or some other free single-page host so there's no need to manually build the thing to use it (once, yknow, it's actually finished)
